### ISSUE TITLE
GPU support Error

### ISSUE THREAD

**Issue by HillCat** [sandrohanea/whisper.net#83]
CUDA error 35 at Z:\Projects\sandro\whisper.net\whisper.cpp\ggml-cuda.cu:420: CUDA driver version is insufficient for CUDA runtime version，

In my computer there is no Z driver and path; And I installed CUDA driver is the newest from official site. I was installed whisper.net.Runtime.Cublas, Whisper.net.  version 1.4.5

![image](https://github.com/sandrohanea/whisper.net/assets/41800196/1f254c84-cf9a-45ff-bf7b-835a7f8eb12a)

![image](https://github.com/sandrohanea/whisper.net/assets/41800196/39d6332b-06de-4df0-a368-50a486b6d520)

**Comment by sandrohanea** [comment]
You don't need that virtual drive Z (that is just some generic stacktrace which shows my build VM path).

Can you, please, call nvcc --version to see which version of nvidia driver you have?

Maybe try to re-install CUDA 12.1.1 (that's the latest version, used to build Whisper.net.Runtime.Cublas).

**Comment by HillCat** [comment]
Yes,I solved this, Downgrade the Cuda Version from 12.x to 11.x is OK, because my Nvidia card Driver is lower than 527.41. but use GPU can not increase the process speed ,why ?
